/* autogenerated by Processing revision 1296 on 2025-03-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class perlin_noise extends PApplet {

double scale = 0.01f;

Noise noise;

public void settings()
{
  size(1080, 720);
}

public void setup()
{
  
}

public void draw()
{
  loadPixels();
  for (int j = 0; j < height; j++)
  for (int i = 0; i < width; i++)
  {
    double x = i * scale;
    double y = j * scale;
    double z = 0.01f * frameCount;

    double v = 0.5f * noise.noise(x, y, z) + 0.5f;

    pixels[j * width + i] = RGB((int)(255 * v));
  }
  updatePixels();
}

public int RGB(int b)
{
  final int a = 255 << 24;
  b = clamp(b, 0, 255);
  return a | (b << 16) | (b << 8) | b;
}

public int RGB(int r, int g, int b)
{
  final int a = 255 << 24;
  r = clamp(r, 0, 255);
  g = clamp(g, 0, 255);
  b = clamp(b, 0, 255);
  return a | (r << 16) | (g << 8) | b;
}

public int RGB(int a, int r, int g, int b)
{
  a = clamp(a, 0, 255);
  r = clamp(r, 0, 255);
  g = clamp(g, 0, 255);
  b = clamp(b, 0, 255);
  return (a << 24) | (r << 16) | (g << 8) | b;
}

public int clamp(int v, int min, int max)
{
  return min(max(v, min), max);
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "perlin_noise" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
