/* autogenerated by Processing revision 1296 on 2025-03-09 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class vector_field extends PApplet {

int grid_size = 20;

double scale = 0.003f;

Noise noise;

public void settings()
{
  size(1080, 720);
}

public void setup()
{
  
}

public void draw()
{
  background(255);

  fill(0);

  for (int j = grid_size / 2; j < height; j += grid_size)
  for (int i = grid_size / 2; i < width; i += grid_size)
  {
    double x = i * scale;
    double y = j * scale;
    double z = 0.003f * frameCount;

    double d = TWO_PI * noise.noise(x, y, z);
    double m = grid_size * noise.noise(x + 1000, y, z);

    double dx = Math.cos(d);
    double dy = Math.sin(d);

    double vx = m * dx;
    double vy = m * dy;

    line(i, j, (int)(i + vx), (int)(j + vy));
    triangle(
      (int)(i + vx), (int)(j + vy),
      (int)(i + 0.7f * vx + 0.15f * vy), (int)(j + 0.7f * vy - 0.15f * vx),
      (int)(i + 0.7f * vx - 0.15f * vy), (int)(j + 0.7f * vy + 0.15f * vx)
    );
  }
}

public int RGB(int b)
{
  final int a = 255 << 24;
  b = clamp(b, 0, 255);
  return a | (b << 16) | (b << 8) | b;
}

public int RGB(int r, int g, int b)
{
  final int a = 255 << 24;
  r = clamp(r, 0, 255);
  g = clamp(g, 0, 255);
  b = clamp(b, 0, 255);
  return a | (r << 16) | (g << 8) | b;
}

public int RGB(int a, int r, int g, int b)
{
  a = clamp(a, 0, 255);
  r = clamp(r, 0, 255);
  g = clamp(g, 0, 255);
  b = clamp(b, 0, 255);
  return (a << 24) | (r << 16) | (g << 8) | b;
}

public int clamp(int v, int min, int max)
{
  return min(max(v, min), max);
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "vector_field" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
